# Cloudflare Workers 配置文件
name = "ai-chat-worker"
main = "worker.js"
compatibility_date = "2023-12-01"

# 环境变量设置（在Cloudflare Dashboard中配置）
[vars]
# OPENAI_API_KEY 将通过 wrangler secret 命令设置

# KV 存储（可选，用于会话管理）
# [[kv_namespaces]]
# binding = "CHAT_SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# 部署设置
[env.production]
name = "ai-chat-worker"
route = "your-domain.com/api/*"  # 替换为您的域名

[env.dev]
name = "ai-chat-worker-dev"